name: Python application

on:
  push:
    branches:
    - main

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022, windows-2019, ubuntu-24.04, ubuntu-22.04, macos-15, macos-14]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pymupdf==1.24.12

    - name: Test dependency
      run: |
        python -c "import pymupdf; print(pymupdf.__version__)"