name: Python application

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pymupdf==1.24.12

    - name: Test dependency
      run: |
        python -c "import pymupdf; print(pymupdf.__version__)"